# This is a basic workflow to help you get started with Actions

name: OSSIBOT Audit
secrets:
  OSSIEBOT_ID:
    required: true
  
  
runs: ubuntu-latest
  using: composite
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
 
      # Install OssiBOT
      - name: install ossie bot client
        run: pip3 install ossie
        shell: bash
        
      # Audit the Repository
      - name: Audit project dependencies
        run: ossie audit --id ${{ secrets.OSSIEBOT_ID }} --project ${{ github.repository }}
        shell: bash
