# This is a basic workflow to help you get started with Actions

name: OSSIBOT Audit
input: 
  OSSIEBOT_ID:
    required: true
runs:
  using: composite
  steps: 
        # Install OssiBOT
    - name: install ossie bot client
      run: pip3 install ossie
      shell: bash

#     # Audit the Repository
    - name: Audit project dependencies
      run: ossie audit --id ${{ OSSIEBOT_ID }} --project ${{ github.repository }}
      shell: bash
